apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: my-connect-cluster
  name: inventory-connector-oracle
spec:
  class: io.debezium.connector.oracle.OracleConnector
  tasksMax: 1
  config:  
    poll.interval.ms: 10000
    table.include.list: 'C##DBZUSER.CUSTOMERS1'
    database.hostname: 5.tcp.eu.ngrok.io
    skip.messages.without.change: true
    offset.flush.interval.ms: 10000
    column.exclude.list: 'C##DBZUSER.CUSTOMERS1.CITY'
    database.password: dbz
    topic.prefix: customer1-connector-oracle
    database.port: 10904
    database.dbname: ORCLCDB
    schema.history.internal.kafka.topic: customers1
    database.user: 'c##dbzuser'
    schema.history.internal.kafka.bootstrap.servers: 'event-broker-dr-kafka-bootstrap.appdev-dbz.svc:9092'
