apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: my-connect-cluster
  name: inventory-connector-oracle
spec:
  class: io.debezium.connector.oracle.OracleConnector
  tasksMax: 1
  config:  
    schema.history.internal.kafka.bootstrap.servers: event-broker-dr-kafka-bootstrap.appdev-dbz.svc:9092
    schema.history.internal.kafka.topic: "schema-changes"
    database.hostname: 2.tcp.eu.ngrok.io
    database.port: 16019
    database.user: c##dbzuser
    database.password: dbz
    database.dbname: ORCLCDB
    topic.prefix: inventory-connector-oracle
    table.include.list: C##DBZUSER.CUSTOMERS